trainer:
  accelerator: gpu
  devices: 1
  max_epochs: 15
  callbacks:
    - class_path: lightning.pytorch.callbacks.ModelCheckpoint
      init_args:
        filename: model
        monitor: segm_prec_iou
        save_weights_only: True
        mode: max
        verbose: True
  logger:
    - class_path: lightning.pytorch.loggers.TensorBoardLogger
      init_args:
        save_dir: /home/home/Documents/Code/cnn-image-segmenter-maskrcnn/ckpt/

model:
  num_classes: 2
  num_channels: 3
  learning_rate: 0.0001
  data_path: /data/path/
  batch_size: 1
  workers: 4
  input_size: 256
